Vagrant.configure("2") do |config|

  config.vm.define "node1" do |node1|
    node1.vm.box="ubuntu/focal64"
    node1.vm.network "forwarded_port", guest: 80, host: 8079

    node1.vm.provider "virtualbox" do |vb|
      vb.cpus = 1
      vb.memory = "1024"
    end
  end
  
  config.vm.define "node2" do |node1|
    node1.vm.box="ubuntu/focal64"
    node1.vm.network "forwarded_port", guest: 80, host: 8081

    node1.vm.provider "virtualbox" do |vb|
      vb.cpus = 1
      vb.memory = "1024"
    end
  end

  config.vm.define "node3" do |node1|
    node1.vm.box="ubuntu/focal64"
    node1.vm.network "forwarded_port", guest: 80, host: 8082

    node1.vm.provider "virtualbox" do |vb|
      vb.cpus = 1
      vb.memory = "1024"
    end
  end

end
